### ISSUE TITLE
Jupyter notebooks break decouple's default config

### ISSUE THREAD

**Issue by tbrodbeck** [HBNetwork/python-decouple#116]
Hi. For some reason jupyter notebooks of vscode the behaviour of decouple recently break decouple default config for me:

```python3
from decouple import config
config('SECRET')
---------------------------------------------------------------------------
/var/folders/hv/j2pkf20x1qb1c0sc23yd58y40000gn/T/ipykernel_9171/3485114881.py in <module>
----> 1 decouple.config('SECRET')

/usr/local/lib/python3.9/site-packages/decouple.py in __call__(self, *args, **kwargs)
    197             self._load(self.search_path or self._caller_path())
    198 
--> 199         return self.config(*args, **kwargs)
    200 
    201 

/usr/local/lib/python3.9/site-packages/decouple.py in __call__(self, *args, **kwargs)
     81         Convenient shortcut to get.
     82         """
---> 83         return self.get(*args, **kwargs)
     84 
     85 

/usr/local/lib/python3.9/site-packages/decouple.py in get(self, option, default, cast)
     66         else:
     67             if isinstance(default, Undefined):
---> 68                 raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
     69 
     70             value = default

UndefinedValueError: SECRET not found. Declare it as envvar or define a default value.
```

I was able to debug the reason for that:
I do not fully understand the purpose of the function, but `AutoConfig._caller_path` returns in a jupyter notebook `/var/folders/hv/j2pkf20x1qb1c0sc23yd58y40000gn/T/ipykernel_9888`.  This causes my `.env` file in the same repository as the notebook to not be found.

Instead in the python REPL this function returns an string with a space `' '`, that works.

Thus, in a notebook I can make decouple working again by setting `config = decouple.AutoConfig(' ')`

Versions:
Jupyter Server 1.9.0
Python 3.9.6
python-decouple==3.4

**Comment by henriquebastos** [comment]
@tbrodbeck this is not a bug. Your fix is the proper way to use decouple with Jupyter. Maybe you can provide a PR to the README to instruct people to avoid this mistake.

**Comment by LY081121** [comment]
Is there any update on this issue? I've tried the workaround on Google Collab but it did not work. Am I not understanding the message correctly?
`from decouple import config
config = decouple.AutoConfig(' ')
config('SECRET')`

**Comment by henriquebastos** [comment]
Decouple's `AutoConfig` searches `.env` starting from the `current working directory` all the way up to your driver's root.
**Jupyter** and **Colab** are servers, so the **current working directory for its processes will not be the directory where your ipnb files are**. 

That is the problem.

You will have to tell decouple to load the right file explicitly:

```python
from decouple import Config, RepositoryEnv
config = Config(RepositoryEnv("/Users/me/project/where/my/env/file/is/.env")
```
