### ISSUE TITLE
Pycharm and the python-decouple package

### ISSUE THREAD

**Issue by cicerohr** [HBNetwork/python-decouple#136]
This is not a package issue, but it occurred in the Pycharm IDE and Python 3.10, where despite the package being manually listed in the requirements.txt file, the IDE warns that the package is not.

The screenshot below shows that the IDE is looking for the package \venv\Lib\site-packages\decouple.py

Again, this is not really a problem, but just a report of IDE behavior.

Any idea?

By the way, thank you very much for developing this package.

![pycharm_decouple](https://user-images.githubusercontent.com/4173604/168674828-ba7daabd-3d70-4de4-a494-50fab63d69b5.png)

**Comment by aqeelat** [comment]
I'm having this issue with most packages that have a module name that's different than the package name. In this case, the package name is `python-decouple`, but the module name is `decouple`. Did you raise this issue with jetbrains?

**Comment by henriquebastos** [comment]
@cicerohr I use PyCharm and never had this problem. Check if maybe you have installed the `decouple` library instead of `python-decouple`.
