### ISSUE TITLE
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

### ISSUE THREAD

**Issue by harshhes** [HBNetwork/python-decouple#148]
I am getting this error, while i was deploying my project to AWS ec2 . In my local server it works fine, any suggestions?

**Comment by hugopenna** [comment]
hey @harshhes 
Make sure that you have a .env file with your secret_key set in your ec2 machine. 

It's quite common to add you `.env` file to `.gitignore` so it doesn’t get in the production machine.

**Comment by harshhes** [comment]
Hey @hugopenna , Thank you for responding, i can't thank you enough for solving this for me. That was so silly of me to not put .env file in my ec2 Instance, i was roaming around all internet for this.

**Comment by hugopenna** [comment]
No worries, I did that myself a bunch of times.

**Comment by hugopenna** [comment]
@henriquebastos @lucasrcezimbra may you close this issue?
