### ISSUE TITLE
This bugs me so much - Install name differs from package name causing IDE warnings

### ISSUE THREAD

**Issue by jonnyhoff** [HBNetwork/python-decouple#158]
This is a small thing & I love this package but it bugs me so much.

The install name (`python-decouple`) differs from package name (`decouple`) causing IDE warnings.

IDE Screenshot:
![image](https://github.com/HBNetwork/python-decouple/assets/8642945/664f5a6e-ba04-44d4-9dec-f55b4d03fef2)

Every time I use this package I need to select `Ignore this package` on the warning.

**Comment by henriquebastos** [comment]
Sorry, I can't reproduce this. I use Pycharm and never had such a problem. I don't know what IDE you're using.
