### ISSUE TITLE
decouple.UndefinedValueError: SECRET_KEY not found.

### ISSUE THREAD

**Issue by Bodundeft** [HBNetwork/python-decouple#160]
Hey,

I am getting this error: decouple.UndefinedValueError: SECRET_KEY not found.

![image](https://github.com/HBNetwork/python-decouple/assets/101883343/371fb132-578d-4ab0-9ed8-f3248cf4187b)

Please I need assistance on how to resolve this, thanks.

**Comment by hugopenna** [comment]
https://github.com/HBNetwork/python-decouple/issues/99
It could help you.
